title: "Learning-augmented Algorithms: Theory & Applications (LATA)"
preposition: at
description: "Workshop on Learning-augmented Algorithms: Theory and Applications -- June 13, 2025 -- [SIGMETRICS 2025](https://www.sigmetrics.org/sigmetrics2025/)"
baseurl: ""
url: "https://learning-augmented-algorithms.github.io/" # the base hostname & protocol for your site

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.1"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

exclude: [vendor]

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:
  map:
  # Initial map center point
  home_coord: 28.360176, -81.510195
  map_provider: "OpenStreetMap.Mapnik"
  default_zoom: 9

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: 'Learning-augmented Algorithms: Theory and Applications (LATA)'
      img: 'latalogo.png'
      relative_url: /
    links:
      # - name: Call for Posters
      #   relative_url: /cfp/
      - name: Accepted Posters
        relative_url: /talks/poster/
      - name: Program
        relative_url: /program/
      - name: Register
        absolute_url: "https://www.sigmetrics.org/sigmetrics2025/registration.html"
      # - name: Talks
      #   relative_url: /talks/
      # - name: Speakers
      #   relative_url: /speakers/
      - name: Previous Years
        menu:
          - name: 2025 (current)
            disabled: true
          - name: 2024
            relative_url: /2024/
          - name: 2023
            relative_url: /2023/
      # - name: "<b>Current Year</b>"
      #   absolute_url: "https://learning-augmented-algorithms.github.io"

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'splash_2025.jpg'      # inside /assets/images/
      open_graph: 'splash_2025.jpg'  # inside /assets/images/

  # Main landing page
  main:
    logo:
      img: 'splash_2025.jpg'
    links:
      # - name: Call for Posters
      #   relative_url: /cfp/
      - name: Accepted Posters
        relative_url: /talks/poster/
      - name: Program
        relative_url: /program/
      - name: Registration
        absolute_url: 'https://www.sigmetrics.org/sigmetrics2025/registration.html'

  # Information boxes
  # info_bars:
  #   - title: Call for Posters
  #     color: primary
  #     main_only: true
  #     text: |
  #       We invite two types of poster submissions. First, we invite submissions presenting new ideas, work in progress, ongoing research directions, and preliminary results. Second, we invite authors of recently published papers on topics related to [Algorithms with Predictions](https://algorithms-with-predictions.github.io) to present their work as a poster. 

  #       ---

  #       Submissions are due by **May 1st, 2023.**  *Please see the [Call for Posters](cfp/) page for more information and important dates!*
    # - text: Call for Posters alert.
    #   color: warning
    #   pages_only: true

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      - name: Talk
        color: success
      # - name: 5 minute poster talks
      #   color: info
      - name: Transitions
        color: info
      - name: Poster Break
        color: primary
      - name: Remarks
        color: warning

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: true

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 30 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
