title: "Learning-augmented Algorithms: Theory and Applications (LATA)"
preposition: at
description: "Workshop on Learning-augmented Algorithms: Theory and Applications, [ACM SIGMETRICS 2023](https://www.sigmetrics.org/sigmetrics2023/)"
baseurl: ""
url: "https://learning-augmented-algorithms.github.io" # the base hostname & protocol for your site

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.1"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

exclude: [vendor]

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:
  map:
  # Initial map center point
  home_coord: 28.360176, -81.510195
  map_provider: "OpenStreetMap.Mapnik"
  default_zoom: 9

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    # logo:
    #   name: Digital Society Switzerland
    #   # img: ''
    #   url: 'https://digitale-gesellschaft.ch/'
    links:
      - name: Call for Posters
        relative_url: /cfp/
      - name: Program
        relative_url: /program/
      # - name: Committee
      #   relative_url: /committee/
      - name: Registration
        disabled: true
        absolute-url: "https://www.sigmetrics.org/sigmetrics2023/"
      # - name: Talks
      #   relative_url: /talks/
      # - name: Speakers
      #   relative_url: /speakers/
      # - name: Previous Editions
      #   menu:
      #     - name: 2020 (current)
      #       disabled: true
      #     - name: 2019
      #       relative_url: /2019/
      #     - name: 2018
      #       relative_url: /2018/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'splash.png'      # inside /assets/images/
      open_graph: 'splash.png'  # inside /assets/images/

  # Main landing page
  main:
    logo:
      img: 'splash.png'
    links:
      - name: Call for Posters
        relative_url: /cfp/
      - name: Tentative Program
        relative_url: /program/
      - name: Registration
        disabled: true
        absolute_url: 'https://www.sigmetrics.org/sigmetrics2023/'

  # Information boxes
  info_bars:
    - title: Call for Posters
      color: primary
      main_only: true
      text: |
        We invite two types of poster submissions. First, we invite submissions presenting new ideas, work in progress, ongoing research directions, and preliminary results. Second, we invite authors of recently published papers on topics related to [Algorithms with Predictions](https://algorithms-with-predictions.github.io) to present their work as a poster. 

        ---

        Submissions are due by **April 10th, 2023.**  *Please see the [Call for Posters](cfp/) page for more information and important dates!*
    # - text: Call for Posters alert.
    #   color: warning
    #   pages_only: true

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      - name: Talk
        color: success
      - name: Poster
        color: info
      - name: Remarks
        color: warning

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: true
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: true

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 5 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: false
