title: "Learning-augmented Algorithms: Theory and Applications (LATA)"
preposition: at
description: >-
  Workshop on Learning-augmented Algorithms: Theory and Applications, SIGMETRICS 2023
baseurl: "/"
url: "https://learning-augmented-algorithms.github.io" # the base hostname & protocol for your site

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.1"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

exclude: [vendor]

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    # logo:
    #   name: Digital Society Switzerland
    #   # img: ''
    #   url: 'https://digitale-gesellschaft.ch/'
    links:
      - name: Call for Posters
        relative_url: /cfp/
      - name: Program
        relative_url: /program/
      - name: Talks
        relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      - name: Location
        relative_url: /location/
      # - name: Previous Editions
      #   menu:
      #     - name: 2020 (current)
      #       disabled: true
      #     - name: 2019
      #       relative_url: /2019/
      #     - name: 2018
      #       relative_url: /2018/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        relative_url: /program/
      - name: How to get there
        relative_url: /location/
      - name: Tickets
        disabled: true
        absolute_url: ''

  # Information boxes
  info_bars:
    - title: Call for Posters
      color: primary
      main_only: true
      text: |
        We invite two types of poster submissions. First, we invite submissions presenting new ideas, work in progress, ongoing research directions, and preliminary results. Second, we invite authors of recently published papers on topics related to [Algorithms with Predictions](https://algorithms-with-predictions.github.io) to present their work as a poster. 

        ---

        Please see the [Call for Posters](cfp/) for more information and important dates!
    - text: Call for Posters alert.
      color: warning
      pages_only: true

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  map:
    # Initial map center point
    home_coord: 47.37808, 8.53935
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 17

  talks:
    # Talk categories
    main_categories:
      - name: Cat A
        color: info
      - name: Cat B
        color: success

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: true

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
